load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "repro_lib",
    srcs = ["main.go"],
    importpath = "example.com/repro",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/foo",
        "@com_example_thirdparty//:thirdparty",
    ],
)

go_binary(
    name = "repro",
    embed = [":repro_lib"],
    visibility = ["//visibility:public"],
)
