# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
Check that a gazelle:go_naming_convention directive in gazelle_override
is passed to go_repository_config as build_naming_conventions.
"""

TEST = r"""
{
  "name": "build_naming_conventions",
  "modules": [
    {
      "name": "build_naming_conventions",
      "is_root": true,
      "tags": {
        "gazelle_override": [
          {
            "directives": [
              "gazelle:go_naming_convention import"
            ],
            "path": "golang.org/x/mod"
          }
        ],
        "module": [
          {
            "path": "golang.org/x/mod",
            "sum": "h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=",
            "version": "v0.40.0"
          }
        ]
      }
    }
  ],
  "files": {
    "./build_naming_conventions/BUILD.bazel": ""
  },
  "downloads": {
    "https://proxy.golang.org/golang.org/x/mod/@v/v0.40.0.mod": {
      "content": "module golang.org/x/mod\n\ngo 1.25.0\n\nrequire golang.org/x/tools v0.49.0 // tagx:ignore\n",
      "sha256": "7458cd1a66875b76fb962428ffb61aee84acfd871a32e56b4efb43b3b8d2a70d"
    },
    "https://proxy.golang.org/golang.org/x/tools/@v/v0.49.0.mod": {
      "content": "module golang.org/x/tools\n\ngo 1.25.0\n\nrequire (\n\tgithub.com/google/go-cmp v0.6.0\n\tgithub.com/yuin/goldmark v1.4.13\n\tgolang.org/x/mod v0.39.0\n\tgolang.org/x/net v0.58.0\n\tgolang.org/x/sync v0.22.0\n\tgolang.org/x/telemetry v0.0.0-20260811182544-a038080d80e5\n)\n\nrequire golang.org/x/sys v0.47.0 // indirect\n",
      "sha256": "86e34efea35b8aa52aabff0ea18c0ef217f074dff67ef7b4c700ae833968cf62"
    }
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"golang.org/x/mod\",\n\t\"Version\": \"v0.40.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/mod/@v/v0.40.0.mod\",\n\t\"GoVersion\": \"1.25.0\",\n\t\"Sum\": \"h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=\"\n}\n{\n\t\"Path\": \"golang.org/x/tools\",\n\t\"Version\": \"v0.49.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"Indirect\": true,\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/tools/@v/v0.49.0.mod\",\n\t\"GoVersion\": \"1.25.0\"\n}\n"
    }
  },
  "want": {
    "main": {
      "repos": [
        {
          "build_naming_conventions": {
            "org_golang_x_mod": "import"
          },
          "name": "bazel_gazelle_go_repository_config"
        },
        {
          "build_directives": [
            "gazelle:go_naming_convention import"
          ],
          "importpath": "golang.org/x/mod",
          "name": "org_golang_x_mod"
        }
      ],
      "root_module_direct_deps": [
        "org_golang_x_mod"
      ],
      "root_module_direct_dev_deps": []
    }
  }
}
"""
