# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
The deprecated go_deps.config(check_direct_dependencies = "off") still
silences the check comparing go.mod requirements against the versions
of the Bazel modules providing them (here example.com/older v1.5.0 vs
older_dep 1.0.0), with a deprecation notice pointing at checks.
"""

TEST = r"""
{
  "name": "check_direct_dependencies",
  "modules": [
    {
      "name": "root",
      "is_root": true,
      "tags": {
        "config": [
          {
            "check_direct_dependencies": "off"
          }
        ],
        "from_file": [
          {
            "go_mod": "@@root//:go.mod"
          }
        ]
      }
    },
    {
      "name": "older_dep",
      "version": "1.0.0",
      "tags": {
        "from_file": [
          {
            "go_mod": "@@older_dep//:go.mod"
          }
        ]
      }
    }
  ],
  "files": {
    "./older_dep/go.mod": "module example.com/older\n\ngo 1.24.12\n",
    "./root/go.mod": "module example.com/root\n\ngo 1.24.12\n\nrequire example.com/older v1.5.0\n"
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"example.com/older\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/older_dep\",\n\t\"GoMod\": \"/test/go_deps/mod/older_dep/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"example.com/root\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/root\",\n\t\"GoMod\": \"/test/go_deps/mod/root/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n",
      "go mod edit -json -- ./older_dep/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/older\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": null,\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n",
      "go mod edit -json -- ./root/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/root\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": [\n\t\t{\n\t\t\t\"Path\": \"example.com/older\",\n\t\t\t\"Version\": \"v1.5.0\"\n\t\t}\n\t],\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n"
    }
  },
  "want": {
    "main": {
      "print": [
        "go_deps.config(check_direct_dependencies = \"off\") is deprecated, use go_deps.config(checks = \"off\") instead."
      ],
      "root_module_direct_deps": [],
      "root_module_direct_dev_deps": []
    }
  }
}
"""
