# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
Verifies that go_repository_config is initialized with information
about multiple Go modules provided by the same Bazel module.
This is needed so that the Go extension can resolve imports on
the various Go modules, even when their names are unrelated.

In this example, multiple major versions are used (v1 in the root,
v2 in a subdirectory), with a go.work file tying them together.
But this needs to work whenever multiple Go modules are declared
inside a Bazel module, which is basically any time go.work is used.
"""

TEST = r"""
{
  "name": "config_prefix_dirs",
  "modules": [
    {
      "name": "config_prefix_dirs",
      "is_root": true,
      "tags": {
        "from_file": [
          {
            "go_work": "@@config_prefix_dirs//:go.work"
          }
        ]
      }
    }
  ],
  "files": {
    "./config_prefix_dirs/go.mod": "module example.com/config_prefix_dirs\n\ngo 1.25.0\n",
    "./config_prefix_dirs/go.work": "go 1.25.0\n\nuse (\n\t.\n\t./v2\n)\n",
    "./config_prefix_dirs/v2/go.mod": "module example.com/config_prefix_dirs/v2\n\ngo 1.25.0\n"
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"example.com/config_prefix_dirs\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/config_prefix_dirs\",\n\t\"GoMod\": \"/test/go_deps/mod/config_prefix_dirs/go.mod\",\n\t\"GoVersion\": \"1.25.0\"\n}\n{\n\t\"Path\": \"example.com/config_prefix_dirs/v2\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/config_prefix_dirs/v2\",\n\t\"GoMod\": \"/test/go_deps/mod/config_prefix_dirs/v2/go.mod\",\n\t\"GoVersion\": \"1.25.0\"\n}\n{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n",
      "go mod edit -json -- ./config_prefix_dirs/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/config_prefix_dirs\"\n\t},\n\t\"Go\": \"1.25.0\",\n\t\"Require\": null,\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n",
      "go mod edit -json -- ./config_prefix_dirs/v2/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/config_prefix_dirs/v2\"\n\t},\n\t\"Go\": \"1.25.0\",\n\t\"Require\": null,\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n",
      "go work edit -json -- ./config_prefix_dirs/go.work": "{\n\t\"Go\": \"1.25.0\",\n\t\"Use\": [\n\t\t{\n\t\t\t\"DiskPath\": \".\"\n\t\t},\n\t\t{\n\t\t\t\"DiskPath\": \"./v2\"\n\t\t}\n\t],\n\t\"Replace\": null\n}\n"
    }
  },
  "want": {
    "main": {
      "repos": [
        {
          "name": "bazel_gazelle_go_repository_config",
          "dep_files": [
            "go.mod",
            "v2/go.mod"
          ],
          "module_names": {
            "@config_prefix_dirs": "config_prefix_dirs"
          },
          "prefix_dirs": {
            "example.com/config_prefix_dirs/v2": "v2"
          },
          "repo_names": {
            "example.com/config_prefix_dirs": "@config_prefix_dirs",
            "example.com/config_prefix_dirs/v2": "@config_prefix_dirs",
            "go_deps_module_tags": "go_deps_module_tags"
          }
        }
      ]
    }
  }
}
"""
