# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
An empty module.

Tests what happens when go_deps is loaded, but no tags are declared.
The synthetic go_deps_module_tags module must not be indexed for Gazelle.
"""

TEST = r"""
{
  "name": "empty",
  "modules": [
    {
      "name": "empty",
      "is_root": true
    }
  ],
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n"
    }
  },
  "want": {
    "main": {
      "repos": [
        {
          "go_env": {
            "GOROOT_LABEL": "@@go_sdk//:ROOT",
            "GOTOOLCHAIN": "local"
          },
          "importpaths": {},
          "module_names": {},
          "name": "bazel_gazelle_go_repository_config",
          "tool_targets": {}
        }
      ],
      "root_module_direct_deps": [],
      "root_module_direct_dev_deps": []
    }
  }
}
"""
