# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
An empty module.

Tests what happens when go_deps is loaded, but no tags are declared.
"""

TEST = r"""
{
  "name": "empty",
  "modules": [
    {
      "name": "empty",
      "is_root": true
    }
  ],
  "want": [
    {
      "name": "bazel_gazelle_go_repository_config"
    }
  ]
}
"""
