# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
go_deps.from_file in a go_deps usage loaded with dev_dependency = True.
Direct requirements of the go.mod file must be reported as dev
dependencies, otherwise Bazel fails because a root module without a
non-dev usage reports non-dev direct dependencies.
"""

TEST = r"""
{
  "name": "from_file_dev_deps",
  "modules": [
    {
      "name": "root",
      "is_root": true,
      "tags_dev": {
        "from_file": [
          {
            "go_mod": "@@root//:go.mod"
          }
        ]
      }
    }
  ],
  "files": {
    "./root/go.mod": "module example.com/root\n\ngo 1.24.12\n\nrequire golang.org/x/mod v0.40.0\n",
    "./root/go.sum": "golang.org/x/mod v0.40.0 h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=\ngolang.org/x/mod v0.40.0/go.mod h1:0/weTWkPWGBikyTWAX3dkjVztMmBA5hM0DH6BElSupE=\n"
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"example.com/root\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/root\",\n\t\"GoMod\": \"/test/go_deps/mod/root/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"golang.org/x/mod\",\n\t\"Version\": \"v0.40.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/mod/@v/v0.40.0.mod\",\n\t\"GoVersion\": \"1.25.0\",\n\t\"Sum\": \"h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=\",\n\t\"GoModSum\": \"h1:0/weTWkPWGBikyTWAX3dkjVztMmBA5hM0DH6BElSupE=\"\n}\n{\n\t\"Path\": \"golang.org/x/tools\",\n\t\"Version\": \"v0.49.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"Indirect\": true,\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/tools/@v/v0.49.0.mod\",\n\t\"GoVersion\": \"1.25.0\"\n}\n",
      "go mod edit -json -- ./root/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/root\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": [\n\t\t{\n\t\t\t\"Path\": \"golang.org/x/mod\",\n\t\t\t\"Version\": \"v0.40.0\"\n\t\t}\n\t],\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n"
    }
  },
  "want": {
    "main": {
      "repos": [
        {
          "importpath": "golang.org/x/mod",
          "name": "org_golang_x_mod",
          "sum": "h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=",
          "version": "v0.40.0"
        }
      ],
      "root_module_direct_deps": [],
      "root_module_direct_dev_deps": [
        "org_golang_x_mod"
      ]
    }
  }
}
"""
