# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
go_deps.from_file requires the go_mod label to point at a file named
go.mod: the synthetic workspace references the file's directory, where
Go reads go.mod, so any other name would be silently ignored.
"""

TEST = r"""
{
  "name": "from_file_not_go_mod",
  "modules": [
    {
      "name": "root",
      "is_root": true,
      "tags": {
        "from_file": [
          {
            "go_mod": "@@root//:bazel.mod"
          }
        ]
      }
    }
  ],
  "files": {
    "./root/bazel.mod": "module example.com/root\n\ngo 1.24.12\n"
  },
  "executions": {
    "main": {
      "go mod edit -json -- ./root/bazel.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/root\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": null,\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n"
    }
  },
  "want": {
    "main": {
      "fail": [
        "go_deps.from_file requires a 'go.mod' file, not '@@root//:bazel.mod'"
      ]
    }
  }
}
"""
