# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
A gazelle_override directive without the "gazelle:" prefix is invalid
and reported instead of being written to the BUILD file as a comment
that Gazelle ignores.
"""

TEST = r"""
{
  "name": "gazelle_override_invalid_directive",
  "modules": [
    {
      "name": "root",
      "is_root": true,
      "tags": {
        "gazelle_override": [
          {
            "directives": [
              "go_naming_convention import"
            ],
            "path": "golang.org/x/mod"
          }
        ],
        "module": [
          {
            "path": "golang.org/x/mod",
            "sum": "h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=",
            "version": "v0.40.0"
          }
        ]
      }
    }
  ],
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"golang.org/x/mod\",\n\t\"Version\": \"v0.40.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/mod/@v/v0.40.0.mod\",\n\t\"GoVersion\": \"1.25.0\",\n\t\"Sum\": \"h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=\"\n}\n{\n\t\"Path\": \"golang.org/x/tools\",\n\t\"Version\": \"v0.49.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"Indirect\": true,\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/tools/@v/v0.49.0.mod\",\n\t\"GoVersion\": \"1.25.0\"\n}\n"
    }
  },
  "want": {
    "main": {
      "fail": [
        "Invalid Gazelle directive: \"go_naming_convention import\". Gazelle directives must be of the form \"gazelle:key value\"."
      ]
    }
  }
}
"""
