# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
A development version of the Go toolchain, whose version string is not
valid in a go directive. go_deps must not crash and must write a valid
go directive to the synthetic workspace.
"""

TEST = r"""
{
  "name": "go_version_devel",
  "modules": [
    {
      "name": "root",
      "is_root": true,
      "tags": {
        "from_file": [
          {
            "go_mod": "@@root//:go.mod"
          }
        ]
      }
    },
    {
      "name": "dep",
      "version": "1.0.0",
      "tags": {
        "from_file": [
          {
            "go_mod": "@@dep//:go.mod"
          }
        ]
      }
    }
  ],
  "files": {
    "./dep/go.mod": "module example.com/dep\n\ngo 1.24.12\n",
    "./root/go.mod": "module example.com/root\n\ngo 1.24.12\n\nrequire golang.org/x/mod v0.40.0\n",
    "./root/go.sum": "golang.org/x/mod v0.40.0 h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=\ngolang.org/x/mod v0.40.0/go.mod h1:0/weTWkPWGBikyTWAX3dkjVztMmBA5hM0DH6BElSupE=\n"
  },
  "downloads": {
    "https://proxy.golang.org/golang.org/x/mod/@v/v0.40.0.mod": {
      "content": "module golang.org/x/mod\n\ngo 1.25.0\n\nrequire golang.org/x/tools v0.49.0 // tagx:ignore\n",
      "sha256": "7458cd1a66875b76fb962428ffb61aee84acfd871a32e56b4efb43b3b8d2a70d"
    },
    "https://proxy.golang.org/golang.org/x/tools/@v/v0.49.0.mod": {
      "content": "module golang.org/x/tools\n\ngo 1.25.0\n\nrequire (\n\tgithub.com/google/go-cmp v0.6.0\n\tgithub.com/yuin/goldmark v1.4.13\n\tgolang.org/x/mod v0.39.0\n\tgolang.org/x/net v0.58.0\n\tgolang.org/x/sync v0.22.0\n\tgolang.org/x/telemetry v0.0.0-20260811182544-a038080d80e5\n)\n\nrequire golang.org/x/sys v0.47.0 // indirect\n",
      "sha256": "86e34efea35b8aa52aabff0ea18c0ef217f074dff67ef7b4c700ae833968cf62"
    }
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"example.com/dep\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/dep\",\n\t\"GoMod\": \"/test/go_deps/mod/dep/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"example.com/root\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/root\",\n\t\"GoMod\": \"/test/go_deps/mod/root/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"golang.org/x/mod\",\n\t\"Version\": \"v0.40.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/mod/@v/v0.40.0.mod\",\n\t\"GoVersion\": \"1.25.0\",\n\t\"Sum\": \"h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=\",\n\t\"GoModSum\": \"h1:0/weTWkPWGBikyTWAX3dkjVztMmBA5hM0DH6BElSupE=\"\n}\n{\n\t\"Path\": \"golang.org/x/tools\",\n\t\"Version\": \"v0.49.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"Indirect\": true,\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/tools/@v/v0.49.0.mod\",\n\t\"GoVersion\": \"1.25.0\"\n}\n",
      "go mod edit -json -- ./dep/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/dep\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": null,\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n",
      "go mod edit -json -- ./root/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/root\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": [\n\t\t{\n\t\t\t\"Path\": \"golang.org/x/mod\",\n\t\t\t\"Version\": \"v0.40.0\"\n\t\t}\n\t],\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n"
    }
  },
  "go_version_output": "go version go1.28-devel_abc123 linux/amd64",
  "want": {
    "main": {
      "repos": [
        {
          "importpath": "golang.org/x/mod",
          "name": "org_golang_x_mod",
          "sum": "h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=",
          "version": "v0.40.0"
        }
      ],
      "root_module_direct_deps": [
        "org_golang_x_mod"
      ],
      "root_module_direct_dev_deps": []
    }
  }
}
"""
