# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
When a Bazel module exposes multiple Go modules via go.work, do not report
a version conflict between bazel_dep version and go.mod requirements for
those module paths.
"""

TEST = r"""
{
  "name": "go_work_version_skip",
  "modules": [
    {
      "name": "go_work_version_skip",
      "is_root": true,
      "tags": {
        "config": [
          {
            "checks": "error"
          }
        ],
        "from_file": [
          {
            "go_mod": "@@go_work_version_skip//:go.mod"
          }
        ]
      }
    },
    {
      "name": "go_work_dep",
      "version": "2.0.0",
      "tags": {
        "from_file": [
          {
            "go_work": "@@go_work_dep//:go.work"
          }
        ]
      }
    }
  ],
  "files": {
    "./go_work_dep/go.mod": "module example.com/go_work_dep\n\ngo 1.24.12\n",
    "./go_work_dep/go.work": "go 1.24.12\n\nuse (\n\t.\n\t./v2\n)\n",
    "./go_work_dep/v2/go.mod": "module example.com/go_work_dep/v2\n\ngo 1.24.12\n",
    "./go_work_version_skip/go.mod": "module example.com/go_work_version_skip\n\ngo 1.24.12\n\nrequire (\n\texample.com/go_work_dep v1.0.0\n\texample.com/go_work_dep/v2 v2.0.0\n)\n",
    "./go_work_version_skip/go.sum": ""
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"example.com/go_work_dep\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/go_work_dep\",\n\t\"GoMod\": \"/test/go_deps/mod/go_work_dep/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"example.com/go_work_dep/v2\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/go_work_dep/v2\",\n\t\"GoMod\": \"/test/go_deps/mod/go_work_dep/v2/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"example.com/go_work_version_skip\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/go_work_version_skip\",\n\t\"GoMod\": \"/test/go_deps/mod/go_work_version_skip/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n",
      "go mod edit -json -- ./go_work_dep/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/go_work_dep\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": null,\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n",
      "go mod edit -json -- ./go_work_dep/v2/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/go_work_dep/v2\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": null,\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n",
      "go mod edit -json -- ./go_work_version_skip/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/go_work_version_skip\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": [\n\t\t{\n\t\t\t\"Path\": \"example.com/go_work_dep\",\n\t\t\t\"Version\": \"v1.0.0\"\n\t\t},\n\t\t{\n\t\t\t\"Path\": \"example.com/go_work_dep/v2\",\n\t\t\t\"Version\": \"v2.0.0\"\n\t\t}\n\t],\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n",
      "go work edit -json -- ./go_work_dep/go.work": "{\n\t\"Go\": \"1.24.12\",\n\t\"Use\": [\n\t\t{\n\t\t\t\"DiskPath\": \".\"\n\t\t},\n\t\t{\n\t\t\t\"DiskPath\": \"./v2\"\n\t\t}\n\t],\n\t\"Replace\": null\n}\n"
    }
  },
  "want": {
    "main": {
      "repos": [
        {
          "name": "bazel_gazelle_go_repository_config"
        }
      ],
      "root_module_direct_deps": [],
      "root_module_direct_dev_deps": []
    }
  }
}
"""
