# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
go_deps.module tag versions use a leading 'v' (v1.0.0) while Bazel module
versions do not (1.0.0). Matching versions should not be reported as conflicts.

The leading 'v' may also be omitted from go_deps.module tag versions
(0.40.0); go_deps adds it before writing the synthetic go.mod file.
"""

TEST = r"""
{
  "name": "module_tag_version_normalize",
  "modules": [
    {
      "name": "root",
      "is_root": true,
      "tags": {
        "config": [
          {
            "checks": "error"
          }
        ],
        "module": [
          {
            "path": "example.com/matching",
            "sum": "h1:abc123=",
            "version": "v1.0.0"
          },
          {
            "path": "golang.org/x/mod",
            "sum": "h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=",
            "version": "0.40.0"
          }
        ]
      }
    },
    {
      "name": "matching_dep",
      "version": "1.0.0",
      "tags": {
        "from_file": [
          {
            "go_mod": "@@matching_dep//:go.mod"
          }
        ]
      }
    }
  ],
  "files": {
    "./matching_dep/go.mod": "module example.com/matching\n\ngo 1.24.12\n"
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"example.com/matching\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/matching_dep\",\n\t\"GoMod\": \"/test/go_deps/mod/matching_dep/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"golang.org/x/mod\",\n\t\"Version\": \"v0.40.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/mod/@v/v0.40.0.mod\",\n\t\"GoVersion\": \"1.25.0\",\n\t\"Sum\": \"h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=\"\n}\n{\n\t\"Path\": \"golang.org/x/tools\",\n\t\"Version\": \"v0.49.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"Indirect\": true,\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/tools/@v/v0.49.0.mod\",\n\t\"GoVersion\": \"1.25.0\"\n}\n",
      "go mod edit -json -- ./matching_dep/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/matching\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": null,\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n"
    }
  },
  "want": {
    "main": {
      "files": {
        "go.mod": "module go_deps_module_tags\ngo 1.27rc3\nrequire example.com/matching v1.0.0\nrequire golang.org/x/mod v0.40.0\nreplace example.com/matching v1.0.0 =\u003e ./mod/matching_dep"
      },
      "repos": [
        {
          "importpath": "golang.org/x/mod",
          "name": "org_golang_x_mod",
          "sum": "h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=",
          "version": "v0.40.0"
        }
      ],
      "root_module_direct_deps": [
        "org_golang_x_mod"
      ],
      "root_module_direct_dev_deps": []
    }
  }
}
"""
