# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
Tests that go_deps.module.local_path is applied as a directory replacement
in the synthetic workspace and passed through to the declared go_repository
as an absolute path. Relative paths are resolved from the root module's
directory.
"""

TEST = r"""
{
  "name": "module_local_path",
  "modules": [
    {
      "name": "mvs_test",
      "is_root": true,
      "tags": {
        "module": [
          {
            "local_path": "./mod_replaced",
            "path": "golang.org/x/mod",
            "version": "v0.40.0"
          }
        ]
      }
    }
  ],
  "files": {
    "./mvs_test/mod_replaced/go.mod": "module golang.org/x/mod\n\ngo 1.24.12\n"
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"golang.org/x/mod\",\n\t\"Version\": \"v0.40.0\",\n\t\"Replace\": {\n\t\t\"Path\": \"/test/mvs_test/mod_replaced\",\n\t\t\"Dir\": \"/test/mvs_test/mod_replaced\",\n\t\t\"GoMod\": \"/test/mvs_test/mod_replaced/go.mod\",\n\t\t\"GoVersion\": \"1.24.12\"\n\t},\n\t\"Dir\": \"/test/mvs_test/mod_replaced\",\n\t\"GoMod\": \"/test/mvs_test/mod_replaced/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n"
    }
  },
  "want": {
    "main": {
      "files": {
        "go.mod": "module go_deps_module_tags\ngo 1.27rc3\nrequire golang.org/x/mod v0.40.0\nreplace golang.org/x/mod v0.40.0 =\u003e ./mvs_test/mod_replaced"
      },
      "repos": [
        {
          "importpath": "golang.org/x/mod",
          "local_path": "/test/mvs_test/mod_replaced",
          "name": "org_golang_x_mod"
        }
      ],
      "root_module_direct_deps": [
        "org_golang_x_mod"
      ],
      "root_module_direct_dev_deps": []
    }
  }
}
"""
