# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
A very basic use of the go_deps.module tag.

Only one module is declared. No go.mod or go.work file is referenced.
We should get a go_repository just for that module.
"""

TEST = r"""
{
  "name": "module",
  "modules": [
    {
      "name": "root",
      "is_root": true,
      "tags": {
        "module": [
          {
            "path": "golang.org/x/mod",
            "sum": "h1:MECBjubtXD7yj4HrhIUcywNaGeNVUdfVnxmPajOk4yk=",
            "version": "v0.38.0"
          }
        ]
      }
    }
  ],
  "want": [
    {
      "importpath": "golang.org/x/mod",
      "name": "org_golang_x_mod",
      "sum": "h1:MECBjubtXD7yj4HrhIUcywNaGeNVUdfVnxmPajOk4yk=",
      "version": "v0.38.0"
    }
  ]
}
"""
