# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
go_deps.module tag versions use a leading 'v' (v1.0.0) while Bazel module
versions do not (1.0.0). Matching versions should not be reported as conflicts.
Bazel module versions may have extra components (1.0.0.bcr.1 for a patched
registry entry), which still provide the same Go module version.

The leading 'v' may also be omitted from go_deps.module tag versions
(0.40.0); go_deps adds it before writing the synthetic go.mod file.

A Bazel module that is newer than an indirect go.mod requirement
(example.com/newer) is not a conflict either.
"""

TEST = r"""
{
  "name": "module_tag_version_normalize",
  "modules": [
    {
      "name": "root",
      "is_root": true,
      "tags": {
        "config": [
          {
            "checks": "error"
          }
        ],
        "from_file": [
          {
            "go_mod": "@@root//:go.mod"
          }
        ],
        "module": [
          {
            "path": "example.com/matching",
            "sum": "h1:abc123=",
            "version": "v1.0.0"
          },
          {
            "path": "golang.org/x/mod",
            "sum": "h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=",
            "version": "0.40.0"
          }
        ]
      }
    },
    {
      "name": "matching_dep",
      "version": "1.0.0.bcr.1",
      "tags": {
        "from_file": [
          {
            "go_mod": "@@matching_dep//:go.mod"
          }
        ]
      }
    },
    {
      "name": "newer_dep",
      "version": "2.0.0",
      "tags": {
        "from_file": [
          {
            "go_mod": "@@newer_dep//:go.mod"
          }
        ]
      }
    }
  ],
  "files": {
    "./matching_dep/go.mod": "module example.com/matching\n\ngo 1.24.12\n",
    "./newer_dep/go.mod": "module example.com/newer\n\ngo 1.24.12\n",
    "./root/go.mod": "module example.com/root\n\ngo 1.24.12\n\nrequire example.com/newer v1.5.0 // indirect\n"
  },
  "downloads": {
    "https://proxy.golang.org/golang.org/x/mod/@v/v0.40.0.mod": {
      "content": "module golang.org/x/mod\n\ngo 1.25.0\n\nrequire golang.org/x/tools v0.49.0 // tagx:ignore\n",
      "sha256": "7458cd1a66875b76fb962428ffb61aee84acfd871a32e56b4efb43b3b8d2a70d"
    },
    "https://proxy.golang.org/golang.org/x/tools/@v/v0.49.0.mod": {
      "content": "module golang.org/x/tools\n\ngo 1.25.0\n\nrequire (\n\tgithub.com/google/go-cmp v0.6.0\n\tgithub.com/yuin/goldmark v1.4.13\n\tgolang.org/x/mod v0.39.0\n\tgolang.org/x/net v0.58.0\n\tgolang.org/x/sync v0.22.0\n\tgolang.org/x/telemetry v0.0.0-20260811182544-a038080d80e5\n)\n\nrequire golang.org/x/sys v0.47.0 // indirect\n",
      "sha256": "86e34efea35b8aa52aabff0ea18c0ef217f074dff67ef7b4c700ae833968cf62"
    }
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"example.com/matching\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/matching_dep\",\n\t\"GoMod\": \"/test/go_deps/mod/matching_dep/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"example.com/newer\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/newer_dep\",\n\t\"GoMod\": \"/test/go_deps/mod/newer_dep/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"example.com/root\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/root\",\n\t\"GoMod\": \"/test/go_deps/mod/root/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"golang.org/x/mod\",\n\t\"Version\": \"v0.40.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/mod/@v/v0.40.0.mod\",\n\t\"GoVersion\": \"1.25.0\",\n\t\"Sum\": \"h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=\"\n}\n{\n\t\"Path\": \"golang.org/x/tools\",\n\t\"Version\": \"v0.49.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"Indirect\": true,\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/tools/@v/v0.49.0.mod\",\n\t\"GoVersion\": \"1.25.0\"\n}\n",
      "go mod edit -json -- ./matching_dep/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/matching\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": null,\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n",
      "go mod edit -json -- ./newer_dep/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/newer\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": null,\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n",
      "go mod edit -json -- ./root/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/root\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": [\n\t\t{\n\t\t\t\"Path\": \"example.com/newer\",\n\t\t\t\"Version\": \"v1.5.0\",\n\t\t\t\"Indirect\": true\n\t\t}\n\t],\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n"
    }
  },
  "want": {
    "main": {
      "repos": [
        {
          "importpath": "golang.org/x/mod",
          "name": "org_golang_x_mod",
          "sum": "h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=",
          "version": "v0.40.0"
        }
      ],
      "root_module_direct_deps": [
        "org_golang_x_mod"
      ],
      "root_module_direct_dev_deps": []
    }
  }
}
"""
