# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
A go_deps.module tag with local_path conflicts with a replace directive
for the same Go module in the root module's go.mod file.
"""

TEST = r"""
{
  "name": "module_local_path_conflict",
  "modules": [
    {
      "name": "root",
      "is_root": true,
      "tags": {
        "from_file": [
          {
            "go_mod": "@@root//:go.mod"
          }
        ],
        "module": [
          {
            "local_path": "./mod_replaced",
            "path": "golang.org/x/mod",
            "version": "v0.40.0"
          }
        ]
      }
    }
  ],
  "files": {
    "./root/go.mod": "module example.com/root\n\ngo 1.24.12\n\nrequire golang.org/x/mod v0.40.0\n\nreplace golang.org/x/mod =\u003e ./other_replaced\n",
    "./root/mod_replaced/go.mod": "module golang.org/x/mod\n\ngo 1.24.12\n",
    "./root/other_replaced/go.mod": "module golang.org/x/mod\n\ngo 1.24.12\n"
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"example.com/root\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/root\",\n\t\"GoMod\": \"/test/go_deps/mod/root/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"golang.org/x/mod\",\n\t\"Version\": \"v0.40.0\",\n\t\"Replace\": {\n\t\t\"Path\": \"/test/root/other_replaced\",\n\t\t\"Dir\": \"/test/root/other_replaced\",\n\t\t\"GoMod\": \"/test/root/other_replaced/go.mod\",\n\t\t\"GoVersion\": \"1.24.12\"\n\t},\n\t\"Dir\": \"/test/root/other_replaced\",\n\t\"GoMod\": \"/test/root/other_replaced/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n",
      "go mod edit -json -- ./root/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/root\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": [\n\t\t{\n\t\t\t\"Path\": \"golang.org/x/mod\",\n\t\t\t\"Version\": \"v0.40.0\"\n\t\t}\n\t],\n\t\"Exclude\": null,\n\t\"Replace\": [\n\t\t{\n\t\t\t\"Old\": {\n\t\t\t\t\"Path\": \"golang.org/x/mod\"\n\t\t\t},\n\t\t\t\"New\": {\n\t\t\t\t\"Path\": \"./other_replaced\"\n\t\t\t}\n\t\t}\n\t],\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n"
    }
  },
  "want": {
    "main": {
      "fail": [
        "golang.org/x/mod: Go module has a local path set by both go_deps.module.local_path and a replace directive in the root module"
      ]
    }
  }
}
"""
