# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
Minimal version selection across Bazel modules.

The root module requires golang.org/x/sync at a low version via from_file.
A dependency Bazel module requires the same Go module at a higher version via
a module tag. go_deps should select the higher version.
"""

TEST = r"""
{
  "name": "mvs",
  "modules": [
    {
      "name": "mvs_test",
      "is_root": true,
      "tags": {
        "config": [
          {}
        ],
        "from_file": [
          {
            "go_mod": "@@mvs_test//:go.mod"
          }
        ]
      }
    },
    {
      "name": "mvs_dep",
      "version": "1.0.0",
      "tags": {
        "module": [
          {
            "path": "golang.org/x/sync",
            "sum": "h1:GGz8+XQP4FvTTrjZPzNKTMFtSXH80RAzG+5ghFPgK9w=",
            "version": "v0.11.0"
          }
        ]
      }
    }
  ],
  "files": {
    "./mvs_test/go.mod": "module example.com/mvs_test\n\ngo 1.24.12\n\nrequire golang.org/x/sync v0.3.0\n",
    "./mvs_test/go.sum": "golang.org/x/sync v0.3.0 h1:ftCYgMx6zT/asHUrPw8BLLscYtGznsLAnjq5RH9P66E=\ngolang.org/x/sync v0.3.0/go.mod h1:FU7BRWz2tNW+3quACPkgCx/L+uEAv1htQ0V83Z9Rj+Y=\n"
  },
  "want": [
    {
      "importpath": "golang.org/x/sync",
      "name": "org_golang_x_sync",
      "sum": "h1:GGz8+XQP4FvTTrjZPzNKTMFtSXH80RAzG+5ghFPgK9w=",
      "version": "v0.11.0"
    }
  ]
}
"""
