# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
The root Bazel module depends on Gazelle but does not use go_deps itself.
Bazel does not include the root module in module_ctx.modules in this case.
go_deps must still declare repos for modules required by dependencies.
"""

TEST = r"""
{
  "name": "no_root_usage",
  "modules": [
    {
      "name": "no_root_usage",
      "is_root": true,
      "no_go_deps_usage": true
    },
    {
      "name": "dep",
      "version": "1.0.0",
      "tags": {
        "from_file": [
          {
            "go_mod": "@@dep//:go.mod"
          }
        ]
      }
    }
  ],
  "files": {
    "./dep/go.mod": "module example.com/dep\n\ngo 1.24.12\n\nrequire golang.org/x/mod v0.40.0\n",
    "./dep/go.sum": "golang.org/x/mod v0.40.0 h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=\ngolang.org/x/mod v0.40.0/go.mod h1:0/weTWkPWGBikyTWAX3dkjVztMmBA5hM0DH6BElSupE=\n"
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"example.com/dep\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/dep\",\n\t\"GoMod\": \"/test/go_deps/mod/dep/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"golang.org/x/mod\",\n\t\"Version\": \"v0.40.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/mod/@v/v0.40.0.mod\",\n\t\"GoVersion\": \"1.25.0\",\n\t\"Sum\": \"h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=\",\n\t\"GoModSum\": \"h1:0/weTWkPWGBikyTWAX3dkjVztMmBA5hM0DH6BElSupE=\"\n}\n{\n\t\"Path\": \"golang.org/x/tools\",\n\t\"Version\": \"v0.49.0\",\n\t\"Time\": \"0001-01-01T00:00:00Z\",\n\t\"Indirect\": true,\n\t\"GoMod\": \"/gomodcache/cache/download/golang.org/x/tools/@v/v0.49.0.mod\",\n\t\"GoVersion\": \"1.25.0\"\n}\n",
      "go mod edit -json -- ./dep/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/dep\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": [\n\t\t{\n\t\t\t\"Path\": \"golang.org/x/mod\",\n\t\t\t\"Version\": \"v0.40.0\"\n\t\t}\n\t],\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n"
    }
  },
  "want": {
    "main": {
      "repos": [
        {
          "importpath": "golang.org/x/mod",
          "name": "org_golang_x_mod",
          "sum": "h1:hUv+3cXcdRHz08UmSiOob7sadHig73uo5bkXxQ/tvUs=",
          "version": "v0.40.0"
        },
        {
          "name": "bazel_gazelle_go_repository_config"
        }
      ],
      "root_module_direct_deps": [],
      "root_module_direct_dev_deps": []
    }
  }
}
"""
