# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
A module_override (the same applies to archive_override and
gazelle_override) targets a Go module that is provided by a Bazel module
with go_deps.from_file. go_deps can't apply the override to the Bazel
module, so it reports an error instead of silently ignoring the override.
"""

TEST = r"""
{
  "name": "override_bazel_module",
  "modules": [
    {
      "name": "root",
      "is_root": true,
      "tags": {
        "from_file": [
          {
            "go_mod": "@@root//:go.mod"
          }
        ],
        "module_override": [
          {
            "patches": [
              "//:dep.patch"
            ],
            "path": "example.com/dep"
          }
        ]
      }
    },
    {
      "name": "dep",
      "version": "1.0.0",
      "tags": {
        "from_file": [
          {
            "go_mod": "@@dep//:go.mod"
          }
        ]
      }
    }
  ],
  "files": {
    "./dep/go.mod": "module example.com/dep\n\ngo 1.24.12\n",
    "./root/go.mod": "module example.com/root\n\ngo 1.24.12\n\nrequire example.com/dep v1.0.0\n"
  },
  "executions": {
    "main": {
      "go list -m -json all": "{\n\t\"Path\": \"example.com/dep\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/dep\",\n\t\"GoMod\": \"/test/go_deps/mod/dep/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"example.com/root\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps/mod/root\",\n\t\"GoMod\": \"/test/go_deps/mod/root/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n{\n\t\"Path\": \"go_deps_module_tags\",\n\t\"Main\": true,\n\t\"Dir\": \"/test/go_deps\",\n\t\"GoMod\": \"/test/go_deps/go.mod\",\n\t\"GoVersion\": \"1.24.12\"\n}\n",
      "go mod edit -json -- ./dep/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/dep\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": null,\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n",
      "go mod edit -json -- ./root/go.mod": "{\n\t\"Module\": {\n\t\t\"Path\": \"example.com/root\"\n\t},\n\t\"Go\": \"1.24.12\",\n\t\"Require\": [\n\t\t{\n\t\t\t\"Path\": \"example.com/dep\",\n\t\t\t\"Version\": \"v1.0.0\"\n\t\t}\n\t],\n\t\"Exclude\": null,\n\t\"Replace\": null,\n\t\"Retract\": null,\n\t\"Tool\": null,\n\t\"Ignore\": null\n}\n"
    }
  },
  "want": {
    "main": {
      "fail": [
        "Go module example.com/dep is provided by Bazel module \"dep\", so go_deps.module_override has no effect on it."
      ]
    }
  }
}
"""
