# Generated by //tools/convert-go-deps-test-case. DO NOT EDIT.
# See README.md for instructions.

"""
A go.work file with an absolute use path. go_deps cannot reference
such a go.mod file with a label, so it reports an error instead of
silently misresolving it.
"""

TEST = r"""
{
  "name": "work_use_absolute",
  "modules": [
    {
      "name": "root",
      "is_root": true,
      "tags": {
        "from_file": [
          {
            "go_work": "@@root//:go.work"
          }
        ]
      }
    }
  ],
  "files": {
    "./root/go.work": "go 1.24.12\n\nuse /abs/path/to/mod\n"
  },
  "executions": {
    "main": {
      "go work edit -json -- ./root/go.work": "{\n\t\"Go\": \"1.24.12\",\n\t\"Use\": [\n\t\t{\n\t\t\t\"DiskPath\": \"/abs/path/to/mod\"\n\t\t}\n\t],\n\t\"Replace\": null\n}\n"
    }
  },
  "want": {
    "main": {
      "fail": [
        "in @@root//:go.work, use directive '/abs/path/to/mod' is an absolute path, which is not supported."
      ]
    }
  }
}
"""
