load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "visibility",
    srcs = ["lang.go"],
    importpath = "github.com/bazelbuild/bazel-gazelle/language/bazel/visibility",
    visibility = ["//visibility:public"],
    deps = [
        "//language/defaults",
        "//v2/language",
    ],
)

alias(
    name = "go_default_library",
    actual = ":visibility",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
        "lang.go",
    ],
    visibility = ["//visibility:public"],
)
