load(":globs_test.bzl", "globs_test_suite")
load(":go_deps_test.bzl", "go_deps_test_suite")
load(":goproxy_test.bzl", "goproxy_test_suite")
load(":semver_test.bzl", "semver_test_suite")
load(":utils_test.bzl", "utils_test_suite")

globs_test_suite(name = "globs_test")

go_deps_test_suite(name = "go_deps_test")

goproxy_test_suite(name = "goproxy_test")

semver_test_suite(name = "semver_test")

utils_test_suite(name = "utils_test")
